/**
 * Replaces the generic dataset titles (e.g. "Counting & Probability — Level 5")
 * with concise, descriptive names (under 5 words) generated by Claude from each
 * problem's actual content.
 *
 * Run with: npx tsx src/lib/name-problems.ts
 */

import "dotenv/config";
import Anthropic from "@anthropic-ai/sdk";
import { PrismaClient } from "../generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });
const claude = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const BATCH_SIZE = 20;

// Strip Asymptote diagrams and trim — Claude only needs the gist.
function clean(body: string): string {
  return body.replace(/\[asy\][\s\S]*?\[\/asy\]/gi, " [diagram] ").trim().slice(0, 600);
}

async function nameBatch(
  batch: { id: string; bodyLatex: string }[]
): Promise<Record<string, string>> {
  const problemsText = batch
    .map((p, i) => `Problem ${i + 1} (id: ${p.id}):\n${clean(p.bodyLatex)}`)
    .join("\n\n---\n\n");

  const res = await claude.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 2048,
    tools: [
      {
        name: "set_titles",
        description: "Provide a concise descriptive title for each problem.",
        input_schema: {
          type: "object" as const,
          properties: {
            titles: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  id: { type: "string", description: "The problem id." },
                  title: {
                    type: "string",
                    description:
                      "A descriptive title, UNDER 5 words, capturing what the problem is about (e.g. 'Counting lattice paths', 'Sum of divisors', 'Tangent circle radius'). Title Case. No trailing punctuation.",
                  },
                },
                required: ["id", "title"],
              },
            },
          },
          required: ["titles"],
        },
      },
    ],
    tool_choice: { type: "tool", name: "set_titles" },
    messages: [
      {
        role: "user",
        content: `Give each of these competition math problems a short, specific title (UNDER 5 words each) describing what it's about. Return a title for every id.\n\n${problemsText}`,
      },
    ],
  });

  const tool = res.content.find((b) => b.type === "tool_use");
  if (!tool || tool.type !== "tool_use") return {};
  const out = tool.input as { titles: { id: string; title: string }[] };
  const map: Record<string, string> = {};
  for (const t of out.titles) map[t.id] = t.title.trim();
  return map;
}

async function main() {
  // Only name problems still carrying the generic dataset title ("… — Level N").
  const problems = await prisma.problem.findMany({
    where: { title: { contains: "— Level" } },
    select: { id: true, bodyLatex: true },
    orderBy: { createdAt: "asc" },
  });
  console.log(`Naming ${problems.length} problems in batches of ${BATCH_SIZE}...`);

  let updated = 0;
  for (let i = 0; i < problems.length; i += BATCH_SIZE) {
    const batch = problems.slice(i, i + BATCH_SIZE);
    let titles: Record<string, string> = {};
    try {
      titles = await nameBatch(batch);
    } catch (e) {
      console.warn(`  batch ${i / BATCH_SIZE} failed:`, (e as Error).message);
      continue;
    }

    await Promise.all(
      batch.map((p) => {
        const title = titles[p.id];
        if (!title) return Promise.resolve();
        updated++;
        return prisma.problem.update({ where: { id: p.id }, data: { title } });
      })
    );
    console.log(`  ${Math.min(i + BATCH_SIZE, problems.length)}/${problems.length} done`);
  }

  console.log(`\nDone. Renamed ${updated} problems.`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
